-- 테이블 init
DELETE FROM product_catalog;
DELETE FROM brand;
ALTER TABLE product_catalog AUTO_INCREMENT = 1;
ALTER TABLE brand AUTO_INCREMENT = 1;

-- Brand 데이터
INSERT INTO brand (brand_name, logo_url, created_at, updated_at) VALUES ('Nike', 'https://example.com/nike_logo.png', NOW(), NOW());
INSERT INTO brand (brand_name, logo_url, created_at, updated_at) VALUES ('Adidas', 'https://example.com/adidas_logo.png', NOW(), NOW());
INSERT INTO brand (brand_name, logo_url, created_at, updated_at) VALUES ('Puma', 'https://example.com/puma_logo.png', NOW(), NOW());

-- Product 데이터
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (1, 'Nike Air Force 1', 120.00, 'https://example.com/nike_af1.png', 'Classic white sneakers from Nike.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (1, 'Nike Dunk Low', 110.00, 'https://example.com/nike_dunk.png', 'Popular low-top sneakers.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (1, 'Nike Blazer Mid', 95.00, 'https://example.com/nike_blazer.png', 'Vintage-style basketball shoes.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (1, 'Nike React Element 55', 130.00, 'https://example.com/nike_react.png', 'Comfortable everyday sneakers.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (1, 'Nike Joyride Run Flyknit', 180.00, 'https://example.com/nike_joyride.png', 'Innovative running shoes.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (1, 'Nike Metcon 7', 130.00, 'https://example.com/nike_metcon.png', 'Cross-training shoes for intense workouts.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (1, 'Nike ZoomX Invincible Run Flyknit', 180.00, 'https://example.com/nike_zoomx.png', 'Max cushioning for long runs.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (1, 'Nike Pegasus 38', 120.00, 'https://example.com/nike_pegasus.png', 'Reliable everyday running shoes.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (1, 'Nike ACG Mountain Fly Gore-Tex', 220.00, 'https://example.com/nike_acg.png', 'Durable outdoor hiking shoes.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (1, 'Nike Vaporfly 4% Flyknit', 250.00, 'https://example.com/nike_vaporfly.png', 'Elite racing shoes.', NOW(), NOW(), NOW());

INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (2, 'Adidas Ultraboost 22', 190.00, 'https://example.com/adidas_ultraboost.png', 'Premium running shoes with responsive cushioning.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (2, 'Adidas Stan Smith', 85.00, 'https://example.com/adidas_stansmith.png', 'Iconic classic tennis shoes.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (2, 'Adidas Superstar', 90.00, 'https://example.com/adidas_superstar.png', 'Shell-toe sneakers, a true classic.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (2, 'Adidas NMD_R1', 140.00, 'https://example.com/adidas_nmd.png', 'Modern urban sneakers.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (2, 'Adidas Forum Low', 100.00, 'https://example.com/adidas_forum.png', '80s basketball style.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (2, 'Adidas Gazelle', 80.00, 'https://example.com/adidas_gazelle.png', 'Timeless low-profile trainers.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (2, 'Adidas Terrex Free Hiker', 180.00, 'https://example.com/adidas_terrex.png', 'Lightweight hiking shoes.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (2, 'Adidas Adizero Adios Pro 3', 220.00, 'https://example.com/adidas_adiospro.png', 'Fastest racing shoes for competition.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (2, 'Adidas Continental 80', 80.00, 'https://example.com/adidas_continental.png', 'Retro fitness-inspired shoes.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (2, 'Adidas Campus 80s', 90.00, 'https://example.com/adidas_campus.png', 'Classic suede sneakers.', NOW(), NOW(), NOW());

INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (3, 'Puma Suede Classic', 70.00, 'https://example.com/puma_suede.png', 'Iconic suede sneakers.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (3, 'Puma RS-X', 110.00, 'https://example.com/puma_rsx.png', 'Chunky retro-inspired sneakers.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (3, 'Puma Cali Sport', 85.00, 'https://example.com/puma_cali.png', 'Platform sneakers for a fashion statement.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (3, 'Puma Future Rider Play On', 90.00, 'https://example.com/puma_futurerider.png', 'Colorful and comfortable sneakers.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (3, 'Puma RS-Fast', 120.00, 'https://example.com/puma_rsfast.png', 'Sleek and dynamic sneakers.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (3, 'Puma Mirage Mox', 100.00, 'https://example.com/puma_mirage.png', 'Inspired by DJ culture.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (3, 'Puma Court Star', 75.00, 'https://example.com/puma_courtstar.png', 'Classic tennis court style.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (3, 'Puma Clyde', 80.00, 'https://example.com/puma_clyde.png', 'Basketball legend Walt "Clyde" Frazier''s signature shoe.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (3, 'Puma King', 150.00, 'https://example.com/puma_king.png', 'Legendary football boots.', NOW(), NOW(), NOW());
INSERT INTO product_catalog (ref_brand_id, product_name, base_price, image_url, description, published_at, created_at, updated_at) VALUES (3, 'Puma Wild Rider', 110.00, 'https://example.com/puma_wildrider.png', 'Urban-inspired street style.', NOW(), NOW(), NOW());